version: '3'

services:
  php:
    container_name: php-raytuna
    build: ./docker/php
    volumes:
    - ./raytuna:/var/www

  nginx:
    image: nginx
    container_name: nginx-raytuna
    ports:
    - 8080:80
    volumes:
    - ./raytuna:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host-raytuna
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raytuna_db
      MYSQL_USER: raytuna_db_user
      MYSQL_PASSWORD: raytuna_db_password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 13306:3306